
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/portal_site?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    data-username: root
    data-password: 123456
server:
  port: 8877