// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test2.proto

package com.sq.protobuf;

public final class Taaaa2 {
  private Taaaa2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.SampleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sub_message = 2;</code>
     */
    java.lang.String getSubMessage();
    /**
     * <code>string sub_message = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubMessageBytes();

    /**
     * <code>string name1 = 3;</code>
     */
    java.lang.String getName1();
    /**
     * <code>string name1 = 3;</code>
     */
    com.google.protobuf.ByteString
        getName1Bytes();

    /**
     * <code>string sub_message1 = 4;</code>
     */
    java.lang.String getSubMessage1();
    /**
     * <code>string sub_message1 = 4;</code>
     */
    com.google.protobuf.ByteString
        getSubMessage1Bytes();

    public com.sq.protobuf.Taaaa2.SampleMessage.TestOneofCase getTestOneofCase();

    public com.sq.protobuf.Taaaa2.SampleMessage.TestOneof2Case getTestOneof2Case();
  }
  /**
   * Protobuf type {@code tutorial.SampleMessage}
   */
  public  static final class SampleMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.SampleMessage)
      SampleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SampleMessage.newBuilder() to construct.
    private SampleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SampleMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SampleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 1;
              testOneof_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 2;
              testOneof_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneof2Case_ = 3;
              testOneof2_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneof2Case_ = 4;
              testOneof2_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sq.protobuf.Taaaa2.internal_static_tutorial_SampleMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sq.protobuf.Taaaa2.internal_static_tutorial_SampleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sq.protobuf.Taaaa2.SampleMessage.class, com.sq.protobuf.Taaaa2.SampleMessage.Builder.class);
    }

    private int testOneofCase_ = 0;
    private java.lang.Object testOneof_;
    public enum TestOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      NAME(1),
      SUB_MESSAGE(2),
      TESTONEOF_NOT_SET(0);
      private final int value;
      private TestOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TestOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneofCase forNumber(int value) {
        switch (value) {
          case 1: return NAME;
          case 2: return SUB_MESSAGE;
          case 0: return TESTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneofCase
    getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    private int testOneof2Case_ = 0;
    private java.lang.Object testOneof2_;
    public enum TestOneof2Case
        implements com.google.protobuf.Internal.EnumLite {
      NAME1(3),
      SUB_MESSAGE1(4),
      TESTONEOF2_NOT_SET(0);
      private final int value;
      private TestOneof2Case(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TestOneof2Case valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneof2Case forNumber(int value) {
        switch (value) {
          case 3: return NAME1;
          case 4: return SUB_MESSAGE1;
          case 0: return TESTONEOF2_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneof2Case
    getTestOneof2Case() {
      return TestOneof2Case.forNumber(
          testOneof2Case_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 1) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 1) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 1) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_MESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>string sub_message = 2;</code>
     */
    public java.lang.String getSubMessage() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 2) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string sub_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubMessageBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 2) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 2) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME1_FIELD_NUMBER = 3;
    /**
     * <code>string name1 = 3;</code>
     */
    public java.lang.String getName1() {
      java.lang.Object ref = "";
      if (testOneof2Case_ == 3) {
        ref = testOneof2_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneof2Case_ == 3) {
          testOneof2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string name1 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getName1Bytes() {
      java.lang.Object ref = "";
      if (testOneof2Case_ == 3) {
        ref = testOneof2_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneof2Case_ == 3) {
          testOneof2_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_MESSAGE1_FIELD_NUMBER = 4;
    /**
     * <code>string sub_message1 = 4;</code>
     */
    public java.lang.String getSubMessage1() {
      java.lang.Object ref = "";
      if (testOneof2Case_ == 4) {
        ref = testOneof2_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneof2Case_ == 4) {
          testOneof2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string sub_message1 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSubMessage1Bytes() {
      java.lang.Object ref = "";
      if (testOneof2Case_ == 4) {
        ref = testOneof2_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneof2Case_ == 4) {
          testOneof2_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testOneofCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testOneof_);
      }
      if (testOneofCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, testOneof_);
      }
      if (testOneof2Case_ == 3) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, testOneof2_);
      }
      if (testOneof2Case_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, testOneof2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testOneofCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testOneof_);
      }
      if (testOneofCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, testOneof_);
      }
      if (testOneof2Case_ == 3) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, testOneof2_);
      }
      if (testOneof2Case_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, testOneof2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sq.protobuf.Taaaa2.SampleMessage)) {
        return super.equals(obj);
      }
      com.sq.protobuf.Taaaa2.SampleMessage other = (com.sq.protobuf.Taaaa2.SampleMessage) obj;

      if (!getTestOneofCase().equals(other.getTestOneofCase())) return false;
      switch (testOneofCase_) {
        case 1:
          if (!getName()
              .equals(other.getName())) return false;
          break;
        case 2:
          if (!getSubMessage()
              .equals(other.getSubMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!getTestOneof2Case().equals(other.getTestOneof2Case())) return false;
      switch (testOneof2Case_) {
        case 3:
          if (!getName1()
              .equals(other.getName1())) return false;
          break;
        case 4:
          if (!getSubMessage1()
              .equals(other.getSubMessage1())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (testOneofCase_) {
        case 1:
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SUB_MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getSubMessage().hashCode();
          break;
        case 0:
        default:
      }
      switch (testOneof2Case_) {
        case 3:
          hash = (37 * hash) + NAME1_FIELD_NUMBER;
          hash = (53 * hash) + getName1().hashCode();
          break;
        case 4:
          hash = (37 * hash) + SUB_MESSAGE1_FIELD_NUMBER;
          hash = (53 * hash) + getSubMessage1().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sq.protobuf.Taaaa2.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sq.protobuf.Taaaa2.SampleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SampleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.SampleMessage)
        com.sq.protobuf.Taaaa2.SampleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sq.protobuf.Taaaa2.internal_static_tutorial_SampleMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sq.protobuf.Taaaa2.internal_static_tutorial_SampleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sq.protobuf.Taaaa2.SampleMessage.class, com.sq.protobuf.Taaaa2.SampleMessage.Builder.class);
      }

      // Construct using com.sq.protobuf.Taaaa2.SampleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        testOneofCase_ = 0;
        testOneof_ = null;
        testOneof2Case_ = 0;
        testOneof2_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sq.protobuf.Taaaa2.internal_static_tutorial_SampleMessage_descriptor;
      }

      @java.lang.Override
      public com.sq.protobuf.Taaaa2.SampleMessage getDefaultInstanceForType() {
        return com.sq.protobuf.Taaaa2.SampleMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.sq.protobuf.Taaaa2.SampleMessage build() {
        com.sq.protobuf.Taaaa2.SampleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sq.protobuf.Taaaa2.SampleMessage buildPartial() {
        com.sq.protobuf.Taaaa2.SampleMessage result = new com.sq.protobuf.Taaaa2.SampleMessage(this);
        if (testOneofCase_ == 1) {
          result.testOneof_ = testOneof_;
        }
        if (testOneofCase_ == 2) {
          result.testOneof_ = testOneof_;
        }
        if (testOneof2Case_ == 3) {
          result.testOneof2_ = testOneof2_;
        }
        if (testOneof2Case_ == 4) {
          result.testOneof2_ = testOneof2_;
        }
        result.testOneofCase_ = testOneofCase_;
        result.testOneof2Case_ = testOneof2Case_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sq.protobuf.Taaaa2.SampleMessage) {
          return mergeFrom((com.sq.protobuf.Taaaa2.SampleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sq.protobuf.Taaaa2.SampleMessage other) {
        if (other == com.sq.protobuf.Taaaa2.SampleMessage.getDefaultInstance()) return this;
        switch (other.getTestOneofCase()) {
          case NAME: {
            testOneofCase_ = 1;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case SUB_MESSAGE: {
            testOneofCase_ = 2;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case TESTONEOF_NOT_SET: {
            break;
          }
        }
        switch (other.getTestOneof2Case()) {
          case NAME1: {
            testOneof2Case_ = 3;
            testOneof2_ = other.testOneof2_;
            onChanged();
            break;
          }
          case SUB_MESSAGE1: {
            testOneof2Case_ = 4;
            testOneof2_ = other.testOneof2_;
            onChanged();
            break;
          }
          case TESTONEOF2_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sq.protobuf.Taaaa2.SampleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sq.protobuf.Taaaa2.SampleMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int testOneofCase_ = 0;
      private java.lang.Object testOneof_;
      public TestOneofCase
          getTestOneofCase() {
        return TestOneofCase.forNumber(
            testOneofCase_);
      }

      public Builder clearTestOneof() {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
        return this;
      }

      private int testOneof2Case_ = 0;
      private java.lang.Object testOneof2_;
      public TestOneof2Case
          getTestOneof2Case() {
        return TestOneof2Case.forNumber(
            testOneof2Case_);
      }

      public Builder clearTestOneof2() {
        testOneof2Case_ = 0;
        testOneof2_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 1) {
          ref = testOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneofCase_ == 1) {
            testOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 1) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneofCase_ == 1) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 1;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        if (testOneofCase_ == 1) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneofCase_ = 1;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string sub_message = 2;</code>
       */
      public java.lang.String getSubMessage() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 2) {
          ref = testOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneofCase_ == 2) {
            testOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sub_message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubMessageBytes() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 2) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneofCase_ == 2) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sub_message = 2;</code>
       */
      public Builder setSubMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 2;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sub_message = 2;</code>
       */
      public Builder clearSubMessage() {
        if (testOneofCase_ == 2) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string sub_message = 2;</code>
       */
      public Builder setSubMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneofCase_ = 2;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string name1 = 3;</code>
       */
      public java.lang.String getName1() {
        java.lang.Object ref = "";
        if (testOneof2Case_ == 3) {
          ref = testOneof2_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneof2Case_ == 3) {
            testOneof2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name1 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getName1Bytes() {
        java.lang.Object ref = "";
        if (testOneof2Case_ == 3) {
          ref = testOneof2_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneof2Case_ == 3) {
            testOneof2_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name1 = 3;</code>
       */
      public Builder setName1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneof2Case_ = 3;
        testOneof2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name1 = 3;</code>
       */
      public Builder clearName1() {
        if (testOneof2Case_ == 3) {
          testOneof2Case_ = 0;
          testOneof2_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string name1 = 3;</code>
       */
      public Builder setName1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneof2Case_ = 3;
        testOneof2_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string sub_message1 = 4;</code>
       */
      public java.lang.String getSubMessage1() {
        java.lang.Object ref = "";
        if (testOneof2Case_ == 4) {
          ref = testOneof2_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneof2Case_ == 4) {
            testOneof2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sub_message1 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSubMessage1Bytes() {
        java.lang.Object ref = "";
        if (testOneof2Case_ == 4) {
          ref = testOneof2_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneof2Case_ == 4) {
            testOneof2_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sub_message1 = 4;</code>
       */
      public Builder setSubMessage1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneof2Case_ = 4;
        testOneof2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sub_message1 = 4;</code>
       */
      public Builder clearSubMessage1() {
        if (testOneof2Case_ == 4) {
          testOneof2Case_ = 0;
          testOneof2_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string sub_message1 = 4;</code>
       */
      public Builder setSubMessage1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneof2Case_ = 4;
        testOneof2_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.SampleMessage)
    }

    // @@protoc_insertion_point(class_scope:tutorial.SampleMessage)
    private static final com.sq.protobuf.Taaaa2.SampleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sq.protobuf.Taaaa2.SampleMessage();
    }

    public static com.sq.protobuf.Taaaa2.SampleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SampleMessage>
        PARSER = new com.google.protobuf.AbstractParser<SampleMessage>() {
      @java.lang.Override
      public SampleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SampleMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SampleMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sq.protobuf.Taaaa2.SampleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SampleMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SampleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013test2.proto\022\010tutorial\"|\n\rSampleMessage" +
      "\022\016\n\004name\030\001 \001(\tH\000\022\025\n\013sub_message\030\002 \001(\tH\000\022" +
      "\017\n\005name1\030\003 \001(\tH\001\022\026\n\014sub_message1\030\004 \001(\tH\001" +
      "B\014\n\ntest_oneofB\r\n\013test_oneof2B\031\n\017com.sq." +
      "protobufB\006Taaaa2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_SampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_SampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SampleMessage_descriptor,
        new java.lang.String[] { "Name", "SubMessage", "Name1", "SubMessage1", "TestOneof", "TestOneof2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
